### ISSUE TITLE
Reload in discuss

### ISSUE THREAD

**Issue by EkstromChris** [fishlr/fishlr-web-support#10]
Created a new topic on a lake, but when save the discuss tab didn't reload and show the topic. Had to change tab, and then back again to discuss for it to show.

**Comment by averas** [comment]
This is related to the fact that the asynchronous saving (and indexing) of the post is not complete when you return to the listings page. There are several solutions, either make the call synchronous (might not be such as bad idea), make a short timeout before redirecting back (ugly) and/or make discussions update a regular intervals. It's probably a combination of the first and last option. This is a problem in the regular discussions as well (i.e. when not discussing a single feature) and the solution is probable the same for both.

**Comment by averas** [comment]
Please review the lastest version and close if happy!

**Comment by EkstromChris** [comment]
Works satisfactory
