### ISSUE TITLE
Text doesn't fit on button

### ISSUE THREAD

**Issue by EkstromChris** [fishlr/fishlr-web-support#12]
The "Notification" text up to the right doesn't quite fit (using Chrome  50.0.2661.102 (64-bit))

<img width="160" alt="screen shot 2016-05-29 at 20 52 31" src="https://cloud.githubusercontent.com/assets/6313911/15635478/5345a048-25df-11e6-9f46-8717af08277f.png">

**Comment by averas** [comment]
Test and report/close.

**Comment by EkstromChris** [comment]
Working!
