### ISSUE TITLE
Search auto-complete

### ISSUE THREAD

**Issue by EkstromChris** [fishlr/fishlr-web-support#16]
It's not possible to click on a water name from the drop-down. It works when you go down with the arrow keys. It would be nice just to click on a name from the dropdown and achieve the same thing.

**Comment by averas** [comment]
Hrmm. This works for me... if you mean the search drop down. Browser?

**Comment by EkstromChris** [comment]
It works sometimes, and sometimes not. Trying to see a pattern.

Chrome (Mac) Version 50.0.2661.102 (64-bit)

**Comment by EkstromChris** [comment]
At some point the search dropdown seems to stop working. Now I can't select with the arrow down/enter not click at the search results.

**Comment by averas** [comment]
Can you test this again? There has been some changes made on the component...

**Comment by EkstromChris** [comment]
Nope, still problems

**Comment by averas** [comment]
Can you describe exactly what you do? I am not able to reproduce this...
