### ISSUE TITLE
Empty image

### ISSUE THREAD

**Issue by EkstromChris** [fishlr/fishlr-web-support#17]
I should probably not be possible to upload an empty image (user meda poi), like this one. 

Don't know if I pressed save before the image was done uploading (didn't see anything in the drag-n-drop box). You would most likely want an upload bar in that anyway (regardless of method of selecting file).

**Comment by EkstromChris** [comment]
And follow-up. Can I remove pictures that I've uploaded?

**Comment by averas** [comment]
- [X] Upload feedback.
- [X] Can't save user media without media.

Please test and report/close.
