### ISSUE TITLE
Weird indentation

### ISSUE THREAD

**Issue by EkstromChris** [fishlr/fishlr-web-support#18]
Some strange indentation in the activity-list of a water.
<img width="698" alt="screen shot 2016-05-29 at 23 22 34" src="https://cloud.githubusercontent.com/assets/6313911/15636099/58c23bd4-25f4-11e6-88f8-12179d94d5ab.png">

**Comment by averas** [comment]
Still seeing this on Tolven?

**Comment by EkstromChris** [comment]
Nope, seems to be working.
