### ISSUE TITLE
Color on text vs background - register a catch

### ISSUE THREAD

**Issue by mthure** [fishlr/fishlr-web-support#25]
When register a catch and I type the the fist letter of the method e.g, J for Jerk. Jerk fishing will be marked, but it's really hard to see the text,

![reg_catch](https://cloud.githubusercontent.com/assets/19627562/15658381/4edbf484-26bc-11e6-89ee-03a9a576ea32.png)

**Comment by averas** [comment]
I think this goes for all selects .. good catch!

**Comment by averas** [comment]
I have fixed this "temporarily". I'm going to make an overall review of the style/CSS and visual design before the release, but this is good enough for now. Please review and report/close.
