### ISSUE TITLE
Can't set position of catches and some POIs when using the satellite map

### ISSUE THREAD

**Issue by EkstromChris** [fishlr/fishlr-web-support#33]
Trying to add a catch, but can't set long/lat. Nothing happens when I click on the map.

**Comment by averas** [comment]
Are you clicking ON a water? ;)

**Comment by averas** [comment]
Ah, are you trying to go via the satellite map?

**Comment by EkstromChris** [comment]
Exactly. Just noticed that it works in terrain mode

**Comment by averas** [comment]
If verifies that you are clicking on an actual body of water on the vector based map... need to figure out something for the satellite map.
